[build]
builder = "NIXPACKS"

[deploy]
startCommand = "npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

# Configuración del volumen persistente
[[deploy.volumes]]
name = "whatsapp-auth-data"
mountPath = "/data"

[environments.production]
RAILWAY_STATIC_URL = "${{RAILWAY_STATIC_URL}}"
RAILWAY_PUBLIC_DOMAIN = "${{RAILWAY_PUBLIC_DOMAIN}}"